<?php
/**
 * OrderPrintOrdersLabelsRequestTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  GeminiCommerce\Order
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * order Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace GeminiCommerce\Order\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * OrderPrintOrdersLabelsRequestTest Class Doc Comment
 *
 * @category    Class
 * @description OrderPrintOrdersLabelsRequest
 * @package     GeminiCommerce\Order
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class OrderPrintOrdersLabelsRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "OrderPrintOrdersLabelsRequest"
     */
    public function testOrderPrintOrdersLabelsRequest()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tenant_id"
     */
    public function testPropertyTenantId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "order_numbers"
     */
    public function testPropertyOrderNumbers()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
