<?php
/**
 * OrderApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  GeminiCommerce\Order
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * order Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace GeminiCommerce\Order\Test\Api;

use \GeminiCommerce\Order\Configuration;
use \GeminiCommerce\Order\ApiException;
use \GeminiCommerce\Order\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * OrderApiTest Class Doc Comment
 *
 * @category Class
 * @package  GeminiCommerce\Order
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class OrderApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for approveOrder
     *
     * Approve Order.
     *
     */
    public function testApproveOrder()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for assignShipment
     *
     * Assign Shipment.
     *
     */
    public function testAssignShipment()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for calculateRefund
     *
     * Calculate Refund.
     *
     */
    public function testCalculateRefund()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for cancelFulfillment
     *
     * Cancel Fulfillment.
     *
     */
    public function testCancelFulfillment()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for cancelOrder
     *
     * Cancel Order.
     *
     */
    public function testCancelOrder()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for cancelShipment
     *
     * Cancel Shipment.
     *
     */
    public function testCancelShipment()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for completeShipmentPacking
     *
     * Complete Shipment Packing.
     *
     */
    public function testCompleteShipmentPacking()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createFulfillment
     *
     * Create Fulfillment.
     *
     */
    public function testCreateFulfillment()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createOrder
     *
     * Create Order.
     *
     */
    public function testCreateOrder()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createOrderHistory
     *
     * Create Order History.
     *
     */
    public function testCreateOrderHistory()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createPayment
     *
     * Create Payment.
     *
     */
    public function testCreatePayment()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createPaymentTransaction
     *
     * Create Payment Transaction.
     *
     */
    public function testCreatePaymentTransaction()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createRefund
     *
     * Create Refund.
     *
     */
    public function testCreateRefund()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createRefundTransaction
     *
     * Create Refund Transaction.
     *
     */
    public function testCreateRefundTransaction()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createShipment
     *
     * Create Shipment.
     *
     */
    public function testCreateShipment()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteOrder
     *
     * Delete Order.
     *
     */
    public function testDeleteOrder()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getFulfillment
     *
     * Get Fulfillment.
     *
     */
    public function testGetFulfillment()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getOrder
     *
     * Get Order.
     *
     */
    public function testGetOrder()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getOrderByCartId
     *
     * Get Order by Cart ID.
     *
     */
    public function testGetOrderByCartId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getOrderByOrderNumber
     *
     * Get Order by Order Number.
     *
     */
    public function testGetOrderByOrderNumber()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getPayment
     *
     * Get Payment.
     *
     */
    public function testGetPayment()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getShipment
     *
     * Get Shipment.
     *
     */
    public function testGetShipment()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getTransaction
     *
     * Get Transaction.
     *
     */
    public function testGetTransaction()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for holdOrder
     *
     * Hold Order.
     *
     */
    public function testHoldOrder()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for importOrder
     *
     * Import Order.
     *
     */
    public function testImportOrder()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listFulfillments
     *
     * List Fulfillments.
     *
     */
    public function testListFulfillments()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listOrders
     *
     * List Orders.
     *
     */
    public function testListOrders()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listOrdersByCustomer
     *
     * List Orders by Customer.
     *
     */
    public function testListOrdersByCustomer()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listOrdersByNumbers
     *
     * List Orders by Numbers.
     *
     */
    public function testListOrdersByNumbers()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listShipments
     *
     * List Shipments.
     *
     */
    public function testListShipments()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for orderAddDocument
     *
     * Documents.
     *
     */
    public function testOrderAddDocument()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for orderRemoveDocumentByCode
     *
     * .
     *
     */
    public function testOrderRemoveDocumentByCode()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for printOrdersLabels
     *
     * Print Orders Labels.
     *
     */
    public function testPrintOrdersLabels()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for quashFulfillment
     *
     * Quash Fulfillment.
     *
     */
    public function testQuashFulfillment()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for quashShipment
     *
     * Quash Shipment.
     *
     */
    public function testQuashShipment()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for receiveFulfillment
     *
     * Receive Fulfillment.
     *
     */
    public function testReceiveFulfillment()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for reportFulfillmentError
     *
     * Report Fulfillment Error.
     *
     */
    public function testReportFulfillmentError()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for reportFulfillmentNotResolvable
     *
     * Report Fulfillment Not Resolvable.
     *
     */
    public function testReportFulfillmentNotResolvable()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for reportFulfillmentReady
     *
     * Report Fulfillment Ready.
     *
     */
    public function testReportFulfillmentReady()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for reportShipmentDelivery
     *
     * Report Shipment Delivery.
     *
     */
    public function testReportShipmentDelivery()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for reportShipmentMissingStock
     *
     * Report Shipment Missing Stock.
     *
     */
    public function testReportShipmentMissingStock()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for resolveShipmentMissingStock
     *
     * Resolve Shipment Missing Stock.
     *
     */
    public function testResolveShipmentMissingStock()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for retryFulfillment
     *
     * Retry Fulfillment.
     *
     */
    public function testRetryFulfillment()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for searchOrders
     *
     * Search Orders.
     *
     */
    public function testSearchOrders()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sendFulfillment
     *
     * Send Fulfillment.
     *
     */
    public function testSendFulfillment()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sendOrderNotification
     *
     * Send Order Notification.
     *
     */
    public function testSendOrderNotification()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for startFulfillmentProcessing
     *
     * Start Fulfillment Processing.
     *
     */
    public function testStartFulfillmentProcessing()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for startShipmentProcessing
     *
     * Start Shipment Processing.
     *
     */
    public function testStartShipmentProcessing()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for unholdOrder
     *
     * Unhold Order.
     *
     */
    public function testUnholdOrder()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateOrder
     *
     * Update Order.
     *
     */
    public function testUpdateOrder()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updatePayment
     *
     * Update Payment.
     *
     */
    public function testUpdatePayment()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
